export { default as Login } from './Login.vue'
export { default as AllSeriesDashboard } from './AllSeriesDashboard.vue'
export { default as SerieDashboard } from './SerieDashboard.vue'
export { default as SerieSettingsDashbaord } from './SerieSettingsDashbaord.vue'
export { default as NewSerie } from './NewSerie.vue'
export { default as NotFound } from './NotFound.vue'
export { default as BadGateway } from './BadGateway.vue'
export { default as Header } from './Header.vue'
