-- ---------------------- --
-- ANICAP DATABASE TABLES --
-- ---------------------- --

CREATE TABLE IF NOT EXISTS app_user (
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  register_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS serie (
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  user_id INT NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  season SMALLINT NOT NULL DEFAULT 0,
  chapter SMALLINT NOT NULL DEFAULT 0,
  score FLOAT NOT NULL DEFAULT 0.0,
  favorite BOOLEAN DEFAULT false,
  wish_to_see BOOLEAN DEFAULT false,
  watch_status TINYINT DEFAULT 0 CHECK (watch_status IN (0, 1, 2)),
  FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE TABLE IF NOT EXISTS migration (
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  migration_name VARCHAR(255) NOT NULL UNIQUE,
  migrated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
