---------------------------
-- ANICAP DATABASE SCRIPTS --
---------------------------

CREATE TABLE IF NOT EXISTS app_user (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  register_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS serie (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  user_id SMALLINT NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  season SMALLINT NOT NULL DEFAULT 0,
  chapter SMALLINT NOT NULL DEFAULT 0,
  score FLOAT NOT NULL DEFAULT 0.0,
  FOREIGN KEY (user_id) REFERENCES app_user (id)
);
